# Generated by Django 4.1.5 on 2023-02-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_bibliotekaalbumow_uzytkownik_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bibliotekaalbumow',
            old_name='library_album_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='bibliotekapiosenek',
            old_name='library_song_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='playlistyuzytkownika',
            old_name='library_playlist_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='subskrypcja',
            old_name='subskrypcja_id',
            new_name='id',
        ),
    ]
