# Generated by Django 4.1.5 on 2023-02-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_album_album_id_alter_autor_autor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utwor',
            name='dlugosc',
            field=models.TimeField(null=True),
        ),
    ]
