# Generated by Django 4.1.5 on 2023-04-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_utwor_dlugosc_autor_rodzaj_autora_utwor_tekst_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utwor',
            old_name='tekst',
            new_name='tekst_sciezka',
        ),
    ]
